# Generated by Django 3.0.7 on 2021-01-15 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')])),
                ('clinic_prefer', models.CharField(choices=[('--The Clinic You Prefer--', '--The Clinic You Prefer--'), ('Princeton', '4499 Rt 27,Princeton'), ('North_Brunswick', '2000 Rt 27,Suite B,North Brunswick')], default='--The Clinic You Prefer--', max_length=30)),
                ('channel', models.CharField(choices=[('--Channel You Find Us--', '--Channel You Find Us--'), ('referred_by_friends', 'referred_by_friends'), ('Insurance_network', 'Insurance_network'), ('Newspaper', 'Newspaper'), ('Internet', 'Internet'), ('Wechat', 'Wechat'), ('Treated_by_Dr_Chen_before', 'Treated_by_Dr_Chen_before'), ('Others', 'Others')], default='--Channel You find Us--', max_length=30)),
                ('message_body', models.TextField()),
                ('is_signed', models.BooleanField(default=False)),
            ],
        ),
    ]
